### ISSUE TITLE
Etapa 1: Creacion de un Header y Footer Sencillo

### ISSUE THREAD

**Issue by adrian33cc** [2santos93/team-react-54#3]
Tal cual solo se necesita un Header y un footer sencillos pero con una consideracion.

En la pantalla de recuperar contraseña el header (nav) debe de tener un botón de iniciar sesión.

**Tambien considerar que en la etapa 2 se requerira que una vez Logueado el usuario se visualizara una miniatura de su fotografia y nick con el que se registro.**

**Comment by roninJosue** [comment]
Trabajaré en este issue.
